const express = require("express");
const controller = require("../controllers/userController");
const router = express.Router();
router.post("/register", controller.register);
router.post("/login", controller.login);
router.post("/reset", controller.reset);
router.put("/reset", controller.resetAction);
router.get("/:ds", controller.getOne);
router.put("/changeInfo", controller.update);
router.delete("/:id", controller.delete);
router.post("/take", controller.takePromotion);
router.get("/", controller.getAll);
module.exports = router;
